# Generated by Django 6.0.1 on 2026-01-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('sku', models.CharField(help_text='Globally unique SKU', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price (decimal for accuracy)', max_digits=10)),
                ('product_type', models.CharField(choices=[('regular', 'Regular'), ('fragile', 'Fragile'), ('perishable', 'Perishable')], help_text='Used to determine low-stock thresholds', max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Minimum stock before alert is triggered')),
                ('has_recent_sales', models.BooleanField(default=False, help_text='Used to filter alerts (Part 3 rule)')),
                ('daily_sales_rate', models.FloatField(default=0, help_text='Average daily sales, used to estimate stockout')),
                ('company', models.ForeignKey(help_text='Company that owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of item in the bundle')),
                ('bundle', models.ForeignKey(help_text='The main bundled product', on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product')),
                ('item', models.ForeignKey(help_text='Product included in the bundle', on_delete=django.db.models.deletion.CASCADE, related_name='included_in', to='products.product')),
            ],
            options={
                'unique_together': {('bundle', 'item')},
            },
        ),
    ]
