# Generated by Django 6.0.1 on 2026-01-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current available stock')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(help_text='Positive or negative stock change')),
                ('reason', models.CharField(help_text='Reason for inventory change', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the inventory change occurred')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Warehouse name (unique per company)', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Optional warehouse location', max_length=255)),
            ],
        ),
    ]
