# Generated by Django 6.0.1 on 2026-01-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier name', max_length=255)),
                ('contact_email', models.EmailField(help_text='Email used for reordering', max_length=254)),
                ('company', models.ForeignKey(help_text='Company this supplier works with', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
